name: '${project.name}'
main: online.unhack.Main
version: '${project.version}'
api-version: 1.19
authors: [ oCerial ]
description: "Hello, world!"
commands:
  helloworld:
    description: "Sends \"hello world\"!"